### PR TITLE
Adding Multithreading

### PR DESCRIPTION
**Pull request by Emersont1**
hey all

I know this is gaining some traction at the moment, so I thought I'd add some multithreading to try and make it run faster / more efficiently

I'm not going to merge this in until I've had several people test this, so I'd appreciate feedback in the comments

Installing:

```bash
# clone the repo
git clone https://github.com/Emersont1/itchio

# checkout to multithreading
cd itchio
git checkout multithreading

# create and load a venv
python -m venv venv
source venv/bin/activate

# install
pip install .

# profit?
python -m itchiodl.downloader -k INSERT_API_KEY_HERE
```

### CODE REVIEW

**Comment by Emersont1** [comment]
I'm assuming that is faster than in single-thread mode?

**Comment by mkolassa** [comment]
I was only getting about 30MB/s with the single thread version.

**Comment by lem6ns** [comment]
Having too much jobs set causes ratelimiting (8 works fine, 10 starts giving errors)

**Comment by Emersont1** [comment]
I'll add that into the documentation

**Pull request merged**
