### PR TITLE
Skip non-download urls

### PR DESCRIPTION
**Pull request by ashpieboop**
Example : Songs of the Northlanders has a google sheet copy link (which is not a download) : https://wolfwyzard.itch.io/songs-of-the-northlanders

### CODE REVIEW

**Comment by Emersont1** [comment]
Without causing some pretty major scope bloat, it'd be great if it could download the google sheet

**Comment by ashpieboop** [comment]
I agree, once I've downloaded everything I can, maybe more edge cases like this will come out so I'll wait for that to undraft my PR and I'll create issues for all cases that could use a specialized handler.

**Comment by ashpieboop** [comment]
Actually, users report blocking cases too in #11 so it might as well be merged asap to make the tool usable

**Comment by ThisIsTenou** [comment]
I've been running this fix for 10 minutes now and it works flawlessly.
image

**Comment by Hime0698** [comment]
How do I install this version, I am having that error.

**Comment by bassclarinetl2** [comment]
> How do I install this version, I am having that error.

use [ThisIsTenou](https://github.com/ThisIsTenou)'s fork for as it has the patch already applied. https://github.com/Emersont1/itchio/issues/11#issuecomment-1062414619

**Comment by Hime0698** [comment]
I am not sure if this is the same issue, but I am seeing this:
`Downloading Timebomb - timebomb-web
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itchio/downloader/__main__.py", line 26, in <module>
    lib.download_library()
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itchio/library.py", line 32, in download_library
    game.download(self.login)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itchio/game.py", line 62, in download
    itchio.utils.download(url, path, self.name +" - "+file)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/itchio/utils.py", line 11, in download
    filename = re.search(r'filename="(.+)"', cd).group(1)
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/re.py", line 200, in search
    return _compile(pattern, flags).search(string)
TypeError: expected string or bytes-like object`

**Comment by Hime0698** [comment]
> > How do I install this version, I am having that error.
> 
> use [ThisIsTenou](https://github.com/ThisIsTenou)'s fork for as it has the patch already applied. [#11 (comment)](https://github.com/Emersont1/itchio/issues/11#issuecomment-1062414619)

ah yes, that fixed my issue, thanks!

**Comment by Emersont1** [comment]
Hi Everyone!
Now I've merged in #15, installing normally works fine

**Pull request closed without merging**
