### PR TITLE
Individual game

### PR DESCRIPTION
**Pull request by Emersont1**
#49 
Needs testing

### CODE REVIEW

**Comment by wertercatt** [comment]
> @wertercatt you were interested in this feature, are you able to test that it works?

Installing now

**Comment by wertercatt** [comment]
```
[wertercatt@RGBeast itch.io]$ python -m itchiodl.downloader --help
usage: python -m hstp [-h] [-k API_KEY] [-p PLATFORM] [-j JOBS] [--download-publisher DOWNLOAD_PUBLISHER] [--download-game DOWNLOAD_GAME]

Build an

options:
  -h, --help            show this help message and exit
  -k API_KEY, --api-key API_KEY
                        Use API key instead of username/password
  -p PLATFORM, --platform PLATFORM
                        Platform to download for (default: all), will accept values like 'windows', 'linux', 'osx' and android
  -j JOBS, --jobs JOBS  Number of concurrent downloads, defaults to 4
  --download-publisher DOWNLOAD_PUBLISHER
                        Download all games from a specific publisher
  --download-game DOWNLOAD_GAME
                        Download a specific game, should be in the format publisher.itch.io/game
[wertercatt@RGBeast itch.io]$ python -m itchiodl.downloader --download-publisher https://etra-etra-games.itch.io/
Username: powerkitten
Password:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 66, in <module>
    main()
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 55, in main
    lib.load_game(args.download_publisher)
TypeError: Library.load_game() missing 1 required positional argument: 'title'
```
download-publisher seems non-functional

```
[wertercatt@RGBeast itch.io]$ python -m itchiodl.downloader --download-game https://etra-etra-games.itch.io/flow
Username: powerkitten
Password:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 66, in <module>
    main()
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 58, in main
    lib.load_game(matches.group(1), matches.group(2))
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/library.py", line 47, in load_game
    self.games.append(Game(j["id"]))
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/game.py", line 17, in __init__
    self.data = data["game"]
TypeError: 'int' object is not subscriptable
```

It just dies if the game doesn't actually have any downloads.

```
[wertercatt@RGBeast itch.io]$ python -m itchiodl.downloader --download-game https://etra-etra-games.itch.io/a-beginners-guide-to-fps-games
Username: powerkitten
Password:
Traceback (most recent call last):
  File "/usr/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 66, in <module>
    main()
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/downloader/__main__.py", line 58, in main
    lib.load_game(matches.group(1), matches.group(2))
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/library.py", line 47, in load_game
    self.games.append(Game(j["id"]))
  File "/home/wertercatt/.local/lib/python3.10/site-packages/itchiodl/game.py", line 17, in __init__
    self.data = data["game"]
TypeError: 'int' object is not subscriptable
```
Nevermind that happens even if there are downloads.

**Comment by wertercatt** [comment]
https://github.com/wertercatt/itchio/commit/64d5f1cdbbda5e261f5537605b7145f7e3b0157c I fixed the issues.

**Comment by Emersont1** [comment]
@wertercatt are you able to open a pull request for it, I can't do it from my end (if you enable allow edits from maintainers that would be smashing too)

**Pull request merged**
